name: Build and deploy ASP.Net Core app to Azure Web App - treinamento690201

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build --configuration Release
        working-directory: ./SEU_DIRETORIO_DO_PROJETO

      - name: dotnet publish
        run: dotnet publish -c Release -o myapp
        working-directory: ./SEU_DIRETORIO_DO_PROJETO

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./SEU_DIRETORIO_DO_PROJETO/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write # This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0BAB5434CA10442EB4A03177B86CA8AE }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_645B3C6316CE4087B77630B881467B4B }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_8EFEAC48D92D44E4B99D99331630A59F }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'treinamento690201'
          slot-name: 'Production'
          package: './myapp'
